version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mathrone # s3의 zip 파일 저장 위치
    overwrite: yes

permissons:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    
hooks:
  ApplicationStart:
    - location: deploy.sh
      runas: ec2-user