version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mathrone
    overwrite: yes

permissons:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: deploy.sh
      runas: ec2-user