version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mathrone
permissons:
  - object: /home/ec2-user/mathrone
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/start.sh
      runas: ec2-user